### ISSUE TITLE
F-droid 发布

### ISSUE THREAD

**Issue by zoenglinghou** [LeetaoGoooo/RSSAid#15]
请问这个程序能通过 F-droid 分发吗？粗略看了一下 Features 感觉 RSSAid 是一个自由软件，完全符合在 F-droid 上分发的标准。

通过 F-droid 分发的话，虽然发布时间会有延迟，但是不用考虑自动更新的问题，也能增加受众面积。

**Comment by LeetaoGoooo** [comment]
> 请问这个程序能通过 F-droid 分发吗？粗略看了一下 Features 感觉 RSSAid 是一个自由软件，完全符合在 F-droid 上分发的标准。
> 
> 通过 F-droid 分发的话，虽然发布时间会有延迟，但是不用考虑自动更新的问题，也能增加受众面积。

之前不知道 F-droid ，简单看了一下应该可以～～后续试着在这个平台发布

**Comment by stonega** [comment]
@zoenglinghou @LeetaoGoooo 发布到 fdroid 我以前有做过，这个 assign 给我吧

**Comment by LeetaoGoooo** [comment]
> @zoenglinghou @LeetaoGoooo 发布到 fdroid 我以前有做过，这个 assign 给我吧

好的～辛苦了，发布正式版本就好了～～pre release 就不用了😂
