### ISSUE TITLE
能否支持导入导出opml格式的rss订阅列表呢

### ISSUE THREAD

**Issue by Ngwind** [LeetaoGoooo/RSSAid#16]

**Comment by LeetaoGoooo** [comment]
rssaid 本身只是一个探测目标网页是否有rss源的软件，每次监测也都是单个链接，所以导入导出 opml 对这个软件没什么使用的场景的吧？

**Comment by Ngwind** [comment]
> rssaid 本身只是一个探测目标网页是否有rss源的软件，每次监测也都是单个链接，所以导入导出 opml 对这个软件没什么使用的场景的吧？

哦明白了，是我搞错了rssid的用法。sorry~
