### ISSUE TITLE
1.5版本无法正常工作

### ISSUE THREAD

**Issue by echsfxy** [LeetaoGoooo/RSSAid#18]
😂1.4正常
使用自己fork挂载于heroku的URL

**Comment by LeetaoGoooo** [comment]
> 😂1.4正常
> 使用自己fork挂载于heroku的URL

1.5 版本和 1.4 版本区别很大，你用 1.5 版本能正常浏览到 rules 吗？

**Comment by echsfxy** [comment]
是设置中的规则?



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月12日(周四) 下午5:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LeetaoGoooo/RSSAid] 1.5版本无法正常工作 (#18)




  
😂1.4正常
 使用自己fork挂载于heroku的URL
  
1.5 版本和 1.4 版本区别很大，你用 1.5 版本能正常浏览到 rules 吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LeetaoGoooo** [comment]
先把这个问题关了，要是后续这个版本还有其他问题～可以在重新 open
