### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by oliroe** [LeetaoGoooo/RSSAid#19]
Hi

Would it be possible to have an English language version of the app. I'm an avid user of RSSHub but it's difficult to use RSSAid when everything is in Chinese/Mandarin (apologies if this is wrong).

Thanks

**Comment by LeetaoGoooo** [comment]
> Hi
> 
> Would it be possible to have an English language version of the app. I'm an avid user of RSSHub but it's difficult to use RSSAid when everything is in Chinese/Mandarin (apologies if this is wrong).
> 
> Thanks

Thank you for your feedback, I will release the English version of the app as soon as possible

**Comment by LeetaoGoooo** [comment]
> Hi
> 
> Would it be possible to have an English language version of the app. I'm an avid user of RSSHub but it's difficult to use RSSAid when everything is in Chinese/Mandarin (apologies if this is wrong).
> 
> Thanks

the latest release has already support English version~hope you enjoy it~
