### ISSUE TITLE
Fastlane suggestions

### ISSUE THREAD

**Issue by IzzySoft** [LeetaoGoooo/RSSAid#27]
Nice to see you're using Fastlane to provide the app's metadata! May I suggest some minor improvements to the structure?

* in `full_description.txt`, please make sure paragraphs are separated by a blank line (and otherwise are kept on one line, as you're having it already). Currently, the second and third paragraph will appear as a single block as there's no separating line.
* screenshots don't need to be duplicated for each locale. If you're using a single set only, it's sufficient to have it inside `en-US` – which is always used as fallback for "missing things". Only "duplicate" to other languages what will be language specific (e.g. having English screenshots in `en-US` and Chinese ones in `zh-CN`
* also don't forget adding new changelogs (by the name `<versionCode>.txt` to the `changelogs` directory before tagging a new release. I doubt the app is still at `versionCode: 1` seeing it has 22 releases :wink:

Thanks!

**Comment by LeetaoGoooo** [comment]
> Nice to see you're using Fastlane to provide the app's metadata! May I suggest some minor improvements to the structure?
> 
> * in `full_description.txt`, please make sure paragraphs are separated by a blank line (and otherwise are kept on one line, as you're having it already). Currently, the second and third paragraph will appear as a single block as there's no separating line.
> * screenshots don't need to be duplicated for each locale. If you're using a single set only, it's sufficient to have it inside `en-US` – which is always used as fallback for "missing things". Only "duplicate" to other languages what will be language specific (e.g. having English screenshots in `en-US` and Chinese ones in `zh-CN`
> * also don't forget adding new changelogs (by the name `<versionCode>.txt` to the `changelogs` directory before tagging a new release. I doubt the app is still at `versionCode: 1` seeing it has 22 releases 😉
> 
> Thanks!

Sorry for late reply and thanks for your advice,i'll take it and refacotor the project structure  as soon as possible when i'm not too busy 😊

**Comment by IzzySoft** [comment]
Oops, looks like you're as busy as I am. So please consider this a "friendly reminder" to not forget about it :smile: Thanks!

**Comment by IzzySoft** [comment]
Thanks for fixing! :smiley: In conjunction with the `versionCode`: You can use that in `changelogs/<versionCode>.txt` to point out what changed in the new version :wink:

**Comment by LeetaoGoooo** [comment]
> Thanks for fixing! 😃 In conjunction with the `versionCode`: You can use that in `changelogs/<versionCode>.txt` to point out what changed in the new version 😉

Okay, thanks for the suggestion, I will do so later or in the next version 😄

**Comment by IzzySoft** [comment]
Wonderful! My updater will pull that along then, and users will see the "whatsNew" section directly below the app description in their F-Droid clients (and on the website). Teaser & appetizer :pizza: :yum: :smile:
