### ISSUE TITLE
生成的 url 里面有多余的 / 分隔符

### ISSUE THREAD

**Issue by Zdbzde** [LeetaoGoooo/RSSAid#29]
RSSAid 生成的 url 前缀为 https://rsshub.app// 多了一个 / 分隔符导致 RSS 阅读器无法直接识别订阅源，需要手动去除 / 后才能使用

**Comment by LeetaoGoooo** [comment]
> RSSAid 生成的 url 前缀为 https://rsshub.app// 多了一个 / 分隔符导致 RSS 阅读器无法直接识别订阅源，需要手动去除 / 后才能使用

一个简单的做法是，在设置中把默认的 domain 的 “/” 去掉，不过考虑在下个版本自动校验去除一下

**Comment by Tuscan-blue** [comment]
输入微博链接，RSSAid生成的url前缀仍然多一个/（https://rsshub.app//）。

**Comment by LeetaoGoooo** [comment]
> 所使用的版本是v1.6.5。输入微博链接，RSSAid生成的url前缀仍然多一个/（https://rsshub.app// ）

okay～我晚点再更新一个版本，修复这个问题吧
