### ISSUE TITLE
versionCode

### ISSUE THREAD

**Issue by IzzySoft** [LeetaoGoooo/RSSAid#32]
It seems like your app's `versionCode` is (almost) never increased; the latest release today again had it at `2`. As Android uses `versionCode` to tell versions apart it's important to increase it with each release. Could you please take care for that? It's the value behind the `+` sign [in this line](https://github.com/LeetaoGoooo/RSSAid/blob/main/pubspec.yaml#L18) of your `pubspec.yaml`. Thanks in advance!

**Comment by IzzySoft** [comment]
Thanks for fixing! Please keep increasing with future releases :smiley:

**Comment by LeetaoGoooo** [comment]
> Thanks for fixing! Please keep increasing with future releases 😃

Okay, no problem! 😄
