### ISSUE TITLE
提交到 F-Droid 主存储库

### ISSUE THREAD

**Issue by linsui** [LeetaoGoooo/RSSAid#33]
因为之前的问题被锁定了，所以我新开了一个。在 F-Droid 的 MR 因为长时间没有回应关闭了，主要问题有两个：

1. 从 GitHub 下载规则文件。这个可以添加一个选项默认禁用，或者 F-Droid 会添加一个 AntiFeature。
2. 请求 android.permission.READ_PHONE_STATE 权限。不知道这个权限是哪来的，应该并不需要。如果不需要的话去掉 https://github.com/LeetaoGoooo/RSSAid/blob/210c4619063cfb1b21ecbded6b96a39a60db27e4/android/app/src/main/AndroidManifest.xml#L46 就可以了。

请问是否仍然愿意在 F-Droid 主存储库里发布应用？我可以帮助打包。谢谢

**Comment by LeetaoGoooo** [comment]
> 因为之前的问题被锁定了，所以我新开了一个。在 F-Droid 的 MR 因为长时间没有回应关闭了，主要问题有两个：
> 
> 1. 从 GitHub 下载规则文件。这个可以添加一个选项默认禁用，或者 F-Droid 会添加一个 AntiFeature。
> 2. 请求 android.permission.READ_PHONE_STATE 权限。不知道这个权限是哪来的，应该并不需要。如果不需要的话去掉 https://github.com/LeetaoGoooo/RSSAid/blob/210c4619063cfb1b21ecbded6b96a39a60db27e4/android/app/src/main/AndroidManifest.xml#L46
>     就可以了。
> 
> 请问是否仍然愿意在 F-Droid 主存储库里发布应用？我可以帮助打包。谢谢

已经把不必要的权限移除了，如果可以帮忙打包的话，自然是再好不过了
