### ISSUE TITLE
规则下载成功并不会立即显示

### ISSUE THREAD

**Issue by linsui** [LeetaoGoooo/RSSAid#34]
规则下载成功并不会立即显示，需要退回主界面再进入规则页面。希望可以改进一下，谢谢！

**Comment by LeetaoGoooo** [comment]
好的～我本周调整一下，然后重新 release 一个版本

**Comment by LeetaoGoooo** [comment]
这个问题已经在 [v1.6.5](https://github.com/LeetaoGoooo/RSSAid/releases/tag/v1.6.5) 修复了
