### ISSUE TITLE
routes does not work

### ISSUE THREAD

**Issue by ippocratis** [LeetaoGoooo/RSSAid#41]
e.g the rsshub route:https://rsshub.app/telegram/channel/rssaid returns an rss feed
But importing https://t.me/rssaid to RSSAid  returns nothing

**Comment by LeetaoGoooo** [comment]
> e.g the rsshub route:https://rsshub.app/telegram/channel/rssaid returns an rss feed But importing https://t.me/rssaid to RSSAid returns nothing

For F-Droid Rules, the application will not fetch rules without permission. You may need to click the 'Refresh' button on the settings page for Rules and then import again~

**Comment by ippocratis** [comment]
I missed an /s/ in telegram link

It needs the web version of the link

**Comment by LeetaoGoooo** [comment]
> I missed an /s/ in telegram link
> 
> It needs the web version of the link

I’m glad that you solved the problem.😊 I’ll close the issue. If you have any other questions, feel free to ask.
