### ISSUE TITLE
点击订阅时，弹出分享的页面

### ISSUE THREAD

**Issue by zuihuanye** [LeetaoGoooo/RSSAid#42]
机器： 荣耀v30 pro
系统： 鸿蒙3.0
[图片](https://imgloc.com/i/hSZSV)

**Comment by LeetaoGoooo** [comment]
> 机器： 荣耀v30 pro 系统： 鸿蒙3.0 [图片](https://imgloc.com/i/hSZSV)

是的，软件本身是不支持订阅的，只是帮助发现 rss ，然后通过分享，让用户自行决定导入订阅软件的
