### ISSUE TITLE
update rules from RSSHub instance's api

### ISSUE THREAD

**Issue by ghost** [LeetaoGoooo/RSSAid#47]
新版RSSHub 设置中，rules是从RSSHub 实例中更新
https://rsshub.yourdomain.com/api/radar/rules
希望能够支持！

**Comment by LeetaoGoooo** [comment]
好的～我近期更新一下

**Comment by LeetaoGoooo** [comment]
@read8873 如果可以的话，可以邮件我一下，发一下最近接口返回的 rules 的数据格式吗？

**Comment by read8873** [comment]
可以参考官方实例的返回 https://rsshub.app/api/radar/rules

**Comment by LeetaoGoooo** [comment]
> 可以参考官方实例的返回，其他私有实例因为配置不一样，部分rules可能不开启 https://rsshub.app/api/radar/rules

收到，感谢，我看一下～～没啥问题的话，明天就把这个问题修复掉

**Comment by read8873** [comment]
感谢！另外好像F-Droid很久没更新啦！

**Comment by read8873** [comment]
感谢！另外好像F-Droid很久没更新啦！
