### ISSUE TITLE
F-Droid update

### ISSUE THREAD

**Issue by linsui** [LeetaoGoooo/RSSAid#53]
I just noticed that the F-Droid version is not updated for a long time because there is no version code bump since v2.0.0. The 2.0.0 apk has version code 1 which is lower than version code 4 of 1.6.5 apk so the update can't be installed. Could you please add version code back and bump it for every update? Thanks!

**Comment by LeetaoGoooo** [comment]
> I just noticed that the F-Droid version is not updated for a long time because there is no version code bump since v2.0.0. The 2.0.0 apk has version code 1 which is lower than version code 4 of 1.6.5 apk so the update can't be installed. Could you please add version code back and bump it for every update? Thanks!

Let me handle it later. There are a few bugs that need to be fixed first. Once they're resolved, I'll release a new version.

**Comment by linsui** [comment]
Ah, the appid is also changed. Is there any special reasons?

**Comment by LeetaoGoooo** [comment]
> Ah, the appid is also changed. Is there any special reasons?

emmm, just because I misspelled my email before ~~

**Comment by linsui** [comment]
If you change the appid then the users won't get the update. :shrug: Do you want it to be included as a new app?

**Comment by LeetaoGoooo** [comment]
> If you change the appid then the users won't get the update. 🤷 Do you want it to be included as a new app?

Sorry for the late reply. I've changed the app ID back. Meanwhile, I fixed some bugs and released a new version.

**Comment by linsui** [comment]
Thanks!

**Comment by LeetaoGoooo** [comment]
> Thanks!

Just to let you know, I noticed that even after changing the app ID back, I still didn't see an update on F-Droid. Is there anything I missed?

**Comment by linsui** [comment]
It takes time to build and publish new versions. :)
