### ISSUE TITLE
[v3.0.0] Unable to get rules.

### ISSUE THREAD

**Issue by echoriiku** [LeetaoGoooo/RSSAid#58]
In the latest v3.0.0 version, I'm unable to get rules, and there's no field to add Access Key/Code for my self-hosted RSSHub instance

![image](https://github.com/user-attachments/assets/1f6bc3ad-ddc7-46d6-9433-223089104d91)
![image](https://github.com/user-attachments/assets/83191982-7c88-4623-b9a8-dbcddb9d0369)

**Comment by LeetaoGoooo** [comment]
> In the latest v3.0.0 version, I'm unable to get rules, and there's no field to add Access Key/Code for my self-hosted RSSHub instance
> 
> ![image](https://private-user-images.githubusercontent.com/42903366/351055332-1f6bc3ad-ddc7-46d6-9433-223089104d91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2ODg0MTYsIm5iZiI6MTcyMTY4ODExNiwicGF0aCI6Ii80MjkwMzM2Ni8zNTEwNTUzMzItMWY2YmMzYWQtZGRjNy00NmQ2LTk0MzMtMjIzMDg5MTA0ZDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDIyNDE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzMDY1MGE5OWZkOGU0MzQ5MjcyZjlkMTRlMTk1OGUxYTM1MGQzNzRkYzUzNjYwNGVlMWQyNjE4NmJkYThlYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t8C-f-MTB8omm01iw8FmpIVNuyJErgdUMJVRHftlkkg) ![image](https://private-user-images.githubusercontent.com/42903366/351055361-83191982-7c88-4623-b9a8-dbcddb9d0369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2ODg0MTYsIm5iZiI6MTcyMTY4ODExNiwicGF0aCI6Ii80MjkwMzM2Ni8zNTEwNTUzNjEtODMxOTE5ODItN2M4OC00NjIzLWI5YTgtZGJjZGRiOWQwMzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDIyNDE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3N2Q3YWE2Y2ZmZjQyYTBmNGYwOTIyOGEyM2IwMmM3N2Q0ZGFjMjJmZTdkMGU4MDg4MjgyN2VhNzhlNTk2OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1DjoM0IhCYsOz0XO-jJPnmCt0soK_XyiNNWt1ed_WoI)

just let you know,for the latest version, RSSAid fetch rules from `https://rsshub.app/api/radar/rules`, so make sure whether you can access this api directly. Or you can set the domain to your own host.it maybe related to this [issue](https://github.com/LeetaoGoooo/RSSAid/issues/47)

**Comment by LeetaoGoooo** [comment]
And for the access code, only when RSSAID detects the rules successfully will it show the config button.

**Comment by echoriiku** [comment]
On my browse I can access the `https://rsshub.app/api/radar/rules` without any issue. I'm not using a vpn or proxy.

**Comment by LeetaoGoooo** [comment]
> On my browse I can access the `https://rsshub.app/api/radar/rules` without any issue. I'm not using a vpn or proxy. ![Screenshot_20240722-200927.png](https://private-user-images.githubusercontent.com/42903366/351136195-e55d0946-6370-4a42-bd8c-f383fa1f3575.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2OTU2NjQsIm5iZiI6MTcyMTY5NTM2NCwicGF0aCI6Ii80MjkwMzM2Ni8zNTExMzYxOTUtZTU1ZDA5NDYtNjM3MC00YTQyLWJkOGMtZjM4M2ZhMWYzNTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDAwNDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NjFkNDE4MWJlNWNlZjdmMmUwMGZhNDZhOWI2NDYwYjQxZTk1Yjc2YTg4NzUxYzU4ZDVmY2NkYTA2ZWVjYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9fukmuZN1Ocb5JFjDwG8xusd4I-1SyX1Gkwebbln1A4)

So you just set the domain to your own self-hosted instance? I saw you raised an issue in Radar https://github.com/DIYgod/RSSHub-Radar/issues/1038. I guess this might be the reason. Let me look at it.

**Comment by echoriiku** [comment]
> So you just set the domain to your own self-hosted instance?  

Yeah, I'm using my own instance. I have Access Key/Code enabled. I think the latest release have some issue with the routes authentication. I can only get to the actual .json file if I manually add `?key=[secret_key]`to my instance url.
Like this `https://personal.instance/api/radar/rules?key=SuperSecretKey`

**Comment by LeetaoGoooo** [comment]
> > So you just set the domain to your own self-hosted instance?
> 
> Yeah, I'm using my own instance. I have Access Key/Code enabled. I think the latest release have some issue with the routes authentication. I can only get to the actual .json file if I manually add `?key=[secret_key]`to my instance url. Like this `https://personal.instance/api/radar/rules?key=SuperSecretKey`

nevertheless, it looks like that rssaid should allow user to set key before fetching rules,let me do that later

**Comment by LeetaoGoooo** [comment]
try this version https://github.com/LeetaoGoooo/RSSAid/releases/tag/v3.0.1%2B10, it may works.

**Comment by echoriiku** [comment]
I just tried, same behavior, but this time in my logs I see that the app tried to get the rules from my self-hosted instance, but failed the authentication (no Access Key)

**Comment by LeetaoGoooo** [comment]
> I just tried, same behavior, but this time in my logs I see that the app tried to get the rules from my self-hosted instance, but failed the authentication (no Access Key)

let me try to add access key in the config page today

**Comment by echoriiku** [comment]
sorry for all the trouble!

**Comment by LeetaoGoooo** [comment]
Haha, don't say that. I'm very happy that you gave me feedback

**Comment by LeetaoGoooo** [comment]
![image](https://github.com/user-attachments/assets/01046ed2-ddad-4d92-b16d-544618785c16)
@echoriiku just let you know, i just  released v3.0.2 version and this version allow user to  set access key in the config page  now. Sorry for later release
