### ISSUE TITLE
3.0版本无法解析 m.bilibili.com 和x.com

### ISSUE THREAD

**Issue by write3371** [LeetaoGoooo/RSSAid#60]

**Comment by LeetaoGoooo** [comment]
有试试 3.0.2 版本吗?

**Comment by LeetaoGoooo** [comment]
> 好像还是不行
把你解析的 link 分享给我，然后确定一下看看你配置页面的规则有加载成功吗～

**Comment by LeetaoGoooo** [comment]
> 这个，会无限转圈卡死，规则json加载成功了 https://m.bilibili.com/space/163637592
> 
> 也许加个timeout 2秒能解决？

很好的建议，我晚点超时的限制

**Comment by LeetaoGoooo** [comment]
> 这个，会无限转圈卡死，规则json加载成功了 https://m.bilibili.com/space/163637592
> 
> 也许加个timeout 2秒能解决？

顺便试一下刷新规则，然后再试试？如果你是从老版本升级过来的话，最新版本的规则可能是之前有变化

**Comment by LeetaoGoooo** [comment]
> 不行，问题依旧

收到，这俩天会在这个 [pr](https://github.com/LeetaoGoooo/RSSAid/pull/61) 里修复掉这个问题

**Comment by LeetaoGoooo** [comment]
![IMG_F74838EE4ADC-1](https://github.com/user-attachments/assets/f814c325-08d0-474d-b4b6-13a961d43ed7)

最新的 3.0.2+12 版本已经修复了这个问题
