### ISSUE TITLE
最新版本中，无法解析链接

### ISSUE THREAD

**Issue by Feng-Xiaohan** [LeetaoGoooo/RSSAid#62]
版本：v3.0.2+12 app-github-release.apk

尝试了包括 网易云音乐、小红书、b站、lofter、晋江文学城等平台，均无法解析出 RSS 源。
部分平台可以出现预览，但在出现之后无限转圈，无法解析。

分别尝试了用自建的服务器和官方提供的服务器，均未能解析。

已手动更新过规则。

![1b3838f5891cef780b49dddad93e096d](https://github.com/user-attachments/assets/4d6bccf4-1688-4553-8119-02dcc8c13d5d)
![03ecadc2221291f2a500c1db4dc3670c](https://github.com/user-attachments/assets/3e1da8aa-b29e-428c-964c-a2e6a4b1b6a1)

**Comment by LeetaoGoooo** [comment]
@Feng-Xiaohan bilibili 的链接我这边测试是没问题的，方便的话可以截图给我看一下规则页面吗？

![Simulator Screenshot - iPhone 15 - 2024-08-19 at 21 58 38](https://github.com/user-attachments/assets/d0b926e4-add9-42be-bfbd-1aed69fa50a3)

**Comment by Feng-Xiaohan** [comment]
> @Feng-Xiaohan bilibili 的链接我这边测试是没问题的，方便的话可以截图给我看一下规则页面吗？
> 
> ![Simulator Screenshot - iPhone 15 - 2024-08-19 at 21 58 38](https://private-user-images.githubusercontent.com/10162120/359127717-d0b926e4-add9-42be-bfbd-1aed69fa50a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNzc2OTksIm5iZiI6MTcyNDA3NzM5OSwicGF0aCI6Ii8xMDE2MjEyMC8zNTkxMjc3MTctZDBiOTI2ZTQtYWRkOS00MmJlLWJmYmQtMWFlZDY5ZmE1MGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE0MjMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkODEwZDM1MmZlYjY1M2JlZTVhMWJmMzc4ZWYxOWM3NjM3OWM3ZWJhMDg3ZDM0MTI2ZTU1NDE0OGU2NTIyNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PtU2QYkz4jWPguRQNVoYdsjeLnEW5qpK02UTXXBC1jA)

没问题！已发。

![c8cc196d5f4bcf59e3784ad24d1d215e](https://github.com/user-attachments/assets/15586220-c543-476e-bfdf-8b61dbc5489e)
![1e5fab96746f649f2ce21f9f9304d261](https://github.com/user-attachments/assets/a5ad18e3-c26c-4bbd-a178-41eb2ce22deb)

刚刚还用 https://rsshub.app 也试了一次，也没能解析……

**Comment by LeetaoGoooo** [comment]
> > @Feng-Xiaohan bilibili 的链接我这边测试是没问题的，方便的话可以截图给我看一下规则页面吗？
> > ![Simulator Screenshot - iPhone 15 - 2024-08-19 at 21 58 38](https://private-user-images.githubusercontent.com/10162120/359127717-d0b926e4-add9-42be-bfbd-1aed69fa50a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNzc2OTksIm5iZiI6MTcyNDA3NzM5OSwicGF0aCI6Ii8xMDE2MjEyMC8zNTkxMjc3MTctZDBiOTI2ZTQtYWRkOS00MmJlLWJmYmQtMWFlZDY5ZmE1MGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE0MjMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkODEwZDM1MmZlYjY1M2JlZTVhMWJmMzc4ZWYxOWM3NjM3OWM3ZWJhMDg3ZDM0MTI2ZTU1NDE0OGU2NTIyNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PtU2QYkz4jWPguRQNVoYdsjeLnEW5qpK02UTXXBC1jA)
> 
> 没问题！已发。
> 
> ![c8cc196d5f4bcf59e3784ad24d1d215e](https://private-user-images.githubusercontent.com/63276191/359137052-15586220-c543-476e-bfdf-8b61dbc5489e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNzgwODQsIm5iZiI6MTcyNDA3Nzc4NCwicGF0aCI6Ii82MzI3NjE5MS8zNTkxMzcwNTItMTU1ODYyMjAtYzU0My00NzZlLWJmZGYtOGI2MWRiYzU0ODllLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE0Mjk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZDQwNGY5MWZlYmUyNjQyZTg1MTA2NjBiNTZmMzE5ZjExNDg2MzU5MGI0NmVmYmJhZGM5NjljODdmYTI2M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uhs_XjRgymUtCwSL942EVo5q2Yi2o-7GhwbIvl_zLqg) ![1e5fab96746f649f2ce21f9f9304d261](https://private-user-images.githubusercontent.com/63276191/359137056-a5ad18e3-c26c-4bbd-a178-41eb2ce22deb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNzgwODQsIm5iZiI6MTcyNDA3Nzc4NCwicGF0aCI6Ii82MzI3NjE5MS8zNTkxMzcwNTYtYTVhZDE4ZTMtYzI2Yy00YmJkLWExNzgtNDFlYjJjZTIyZGViLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE0Mjk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYWI1M2NiZWU4OWM3ZjE0Zjk5YjI0ZTViNWRiN2RjNjI0ZTJlOGNiM2JkYTAyNWY5OGZmY2ZhMjE3YmVmNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LoHVMsQQOSAYVXID_Vn-U87RAI1-4zL2hJcSJLm0Zrk)
> 
> 刚刚还用 https://rsshub.app 也试了一次，也没能解析……


找到问题了，你应该是从老版本升级过来的，规则还是之前的，刷新不会生效的，你这个卸载然后重新安装一下应该就可以了

**Comment by Feng-Xiaohan** [comment]
> @Feng-Xiaohan bilibili 的链接我这边测试是没问题的，方便的话可以截图给我看一下规则页面吗？
> 
> ![Simulator Screenshot - iPhone 15 - 2024-08-19 at 21 58 38](https://private-user-images.githubusercontent.com/10162120/359127717-d0b926e4-add9-42be-bfbd-1aed69fa50a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNzgzMjgsIm5iZiI6MTcyNDA3ODAyOCwicGF0aCI6Ii8xMDE2MjEyMC8zNTkxMjc3MTctZDBiOTI2ZTQtYWRkOS00MmJlLWJmYmQtMWFlZDY5ZmE1MGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE0MzM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNDE1YTc1ZmUwMjI0NDA4YTM4OTRlOWJhZTFmMGVmMDdkYzdjM2Q1MDQ0MTNhZTlkZDczZDQzMGE5ZDAzZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tp9T_8oD8SCnpTgW6Stho3nM2DlSKcZi3hJ2GlDcmJ4)

卸载重装了，但现在我刷新不出规则，一直都是一片空白。
无论是否挂梯子都无法刷出来，请问该怎么处理？

**Comment by Feng-Xiaohan** [comment]
> > > @Feng-Xiaohan bilibili 的链接我这边测试是没问题的，方便的话可以截图给我看一下规则页面吗？
> > > ![Simulator Screenshot - iPhone 15 - 2024-08-19 at 21 58 38](https://private-user-images.githubusercontent.com/10162120/359127717-d0b926e4-add9-42be-bfbd-1aed69fa50a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNzc2OTksIm5iZiI6MTcyNDA3NzM5OSwicGF0aCI6Ii8xMDE2MjEyMC8zNTkxMjc3MTctZDBiOTI2ZTQtYWRkOS00MmJlLWJmYmQtMWFlZDY5ZmE1MGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE0MjMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkODEwZDM1MmZlYjY1M2JlZTVhMWJmMzc4ZWYxOWM3NjM3OWM3ZWJhMDg3ZDM0MTI2ZTU1NDE0OGU2NTIyNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PtU2QYkz4jWPguRQNVoYdsjeLnEW5qpK02UTXXBC1jA)
> > 
> > 
> > 没问题！已发。
> > ![c8cc196d5f4bcf59e3784ad24d1d215e](https://private-user-images.githubusercontent.com/63276191/359137052-15586220-c543-476e-bfdf-8b61dbc5489e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNzgwODQsIm5iZiI6MTcyNDA3Nzc4NCwicGF0aCI6Ii82MzI3NjE5MS8zNTkxMzcwNTItMTU1ODYyMjAtYzU0My00NzZlLWJmZGYtOGI2MWRiYzU0ODllLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE0Mjk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZDQwNGY5MWZlYmUyNjQyZTg1MTA2NjBiNTZmMzE5ZjExNDg2MzU5MGI0NmVmYmJhZGM5NjljODdmYTI2M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uhs_XjRgymUtCwSL942EVo5q2Yi2o-7GhwbIvl_zLqg) ![1e5fab96746f649f2ce21f9f9304d261](https://private-user-images.githubusercontent.com/63276191/359137056-a5ad18e3-c26c-4bbd-a178-41eb2ce22deb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNzgwODQsIm5iZiI6MTcyNDA3Nzc4NCwicGF0aCI6Ii82MzI3NjE5MS8zNTkxMzcwNTYtYTVhZDE4ZTMtYzI2Yy00YmJkLWExNzgtNDFlYjJjZTIyZGViLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE0Mjk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYWI1M2NiZWU4OWM3ZjE0Zjk5YjI0ZTViNWRiN2RjNjI0ZTJlOGNiM2JkYTAyNWY5OGZmY2ZhMjE3YmVmNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LoHVMsQQOSAYVXID_Vn-U87RAI1-4zL2hJcSJLm0Zrk)
> > 刚刚还用 https://rsshub.app 也试了一次，也没能解析……
> 
> 找到问题了，你应该是从老版本升级过来的，规则还是之前的，刷新不会生效的，你这个卸载然后重新安装一下应该就可以了

解决了！！
需要把 url 填为 https://rsshub.app 然后挂梯子，因为我自己的服务器没挂代理。
谢谢大佬！麻烦了！

**Comment by LeetaoGoooo** [comment]
> > > > @Feng-Xiaohan bilibili 的链接我这边测试是没问题的，方便的话可以截图给我看一下规则页面吗？
> > > > ![Simulator Screenshot - iPhone 15 - 2024-08-19 at 21 58 38](https://private-user-images.githubusercontent.com/10162120/359127717-d0b926e4-add9-42be-bfbd-1aed69fa50a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNzc2OTksIm5iZiI6MTcyNDA3NzM5OSwicGF0aCI6Ii8xMDE2MjEyMC8zNTkxMjc3MTctZDBiOTI2ZTQtYWRkOS00MmJlLWJmYmQtMWFlZDY5ZmE1MGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE0MjMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkODEwZDM1MmZlYjY1M2JlZTVhMWJmMzc4ZWYxOWM3NjM3OWM3ZWJhMDg3ZDM0MTI2ZTU1NDE0OGU2NTIyNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PtU2QYkz4jWPguRQNVoYdsjeLnEW5qpK02UTXXBC1jA)
> > > 
> > > 
> > > 没问题！已发。
> > > ![c8cc196d5f4bcf59e3784ad24d1d215e](https://private-user-images.githubusercontent.com/63276191/359137052-15586220-c543-476e-bfdf-8b61dbc5489e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNzgwODQsIm5iZiI6MTcyNDA3Nzc4NCwicGF0aCI6Ii82MzI3NjE5MS8zNTkxMzcwNTItMTU1ODYyMjAtYzU0My00NzZlLWJmZGYtOGI2MWRiYzU0ODllLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE0Mjk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZDQwNGY5MWZlYmUyNjQyZTg1MTA2NjBiNTZmMzE5ZjExNDg2MzU5MGI0NmVmYmJhZGM5NjljODdmYTI2M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uhs_XjRgymUtCwSL942EVo5q2Yi2o-7GhwbIvl_zLqg) ![1e5fab96746f649f2ce21f9f9304d261](https://private-user-images.githubusercontent.com/63276191/359137056-a5ad18e3-c26c-4bbd-a178-41eb2ce22deb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNzgwODQsIm5iZiI6MTcyNDA3Nzc4NCwicGF0aCI6Ii82MzI3NjE5MS8zNTkxMzcwNTYtYTVhZDE4ZTMtYzI2Yy00YmJkLWExNzgtNDFlYjJjZTIyZGViLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE0Mjk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYWI1M2NiZWU4OWM3ZjE0Zjk5YjI0ZTViNWRiN2RjNjI0ZTJlOGNiM2JkYTAyNWY5OGZmY2ZhMjE3YmVmNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LoHVMsQQOSAYVXID_Vn-U87RAI1-4zL2hJcSJLm0Zrk)
> > > 刚刚还用 https://rsshub.app 也试了一次，也没能解析……
> > 
> > 
> > 找到问题了，你应该是从老版本升级过来的，规则还是之前的，刷新不会生效的，你这个卸载然后重新安装一下应该就可以了
> 
> 解决了！！ 需要把 url 填为 https://rsshub.app 然后挂梯子，因为我自己的服务器没挂代理。 谢谢大佬！麻烦了！

哈哈 没关系不用谢，有问题随时反馈
