### ISSUE TITLE
Translating Github addresses incorrectly

### ISSUE THREAD

**Issue by oliroe** [LeetaoGoooo/RSSAid#63]
Hi

When using RSSHub Radar for the following github pull request it correctly translates the address

https://github.com/FlareSolverr/FlareSolverr/pull/1301
into
https://***rsshub***.com/github/comments/FlareSolverr/FlareSolverr/1301
![image](https://github.com/user-attachments/assets/8f66fe28-6580-4f06-9917-daf6fca2308f)

but when using rssaid it translates the address for all pull requests and not #1301
https://***rsshub***.com/github/comments/FlareSolverr/FlareSolverr/pull

![Screenshot_20241008-112055](https://github.com/user-attachments/assets/31a527ea-fa04-4754-93c1-e4e29ef2d83b)

**Comment by LeetaoGoooo** [comment]
> Hi
> 
> When using RSSHub Radar for the following github pull request it correctly translates the address
> 
> [FlareSolverr/FlareSolverr#1301](https://github.com/FlareSolverr/FlareSolverr/pull/1301) into https://_**rsshub**_.com/github/comments/FlareSolverr/FlareSolverr/1301 ![image](https://private-user-images.githubusercontent.com/4500141/374514599-8f66fe28-6580-4f06-9917-daf6fca2308f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODY4NzYsIm5iZiI6MTcyODM4NjU3NiwicGF0aCI6Ii80NTAwMTQxLzM3NDUxNDU5OS04ZjY2ZmUyOC02NTgwLTRmMDYtOTkxNy1kYWY2ZmNhMjMwOGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDhUMTEyMjU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWRkYjdhM2U2MTM3YTBkZjVhZTcxMTE1ZWM4OTk0NDZiOTI4NmY5ZDM1ODdkMGZkYjY4YWE2NjExY2RkOWQxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5ndF1whWQu7Dt4URxmLOTnpEg21Vg-i3_5pvns8dTDE)
> 
> but when using rssaid it translates the address for all pull requests and not #1301 https://_**rsshub**_.com/github/comments/FlareSolverr/FlareSolverr/pull
> 
> ![Screenshot_20241008-112055](https://private-user-images.githubusercontent.com/4500141/374515753-31a527ea-fa04-4754-93c1-e4e29ef2d83b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODY4NzYsIm5iZiI6MTcyODM4NjU3NiwicGF0aCI6Ii80NTAwMTQxLzM3NDUxNTc1My0zMWE1MjdlYS1mYTA0LTQ3NTQtOTNjMS1lNGUyOWVmMmQ4M2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDhUMTEyMjU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2Q4YmNjMDJkZTU1MDQ1YWJjNzQxMWI1M2U4NWNhMjg3OGIyNzVjNzE3N2ZlNDM2NDRiOTJmOGRkOGRhZmJiNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.QSR4YEDKlkp97IwyS6gXuERkuaVwl-iuNtQJ-S1wLPY)

thank you for your feedback, let met check it later .

**Comment by LeetaoGoooo** [comment]
@oliroe  hi man, this should be fixed in the latest version, please let me know if it works for you ~

**Comment by oliroe** [comment]
Appreciate the quick response and all looks good. Only tested it against comments on issues/pull requests but will test everything else. I'll raise a separate issue if I find anything

Thanks again
