### ISSUE TITLE
支持添加多个 rsshub 服务器

### ISSUE THREAD

**Issue by finch71** [LeetaoGoooo/RSSAid#66]
支持添加多个 rsshub 服务器，最好有一个下拉选择框来选择解析当前URL所用的 rsshub 服务器。

**Comment by LeetaoGoooo** [comment]
收到～在下个版本里把这个功能加上～

**Comment by LeetaoGoooo** [comment]
@finch71 新版本已经支持～

**Comment by LeetaoGoooo** [comment]
> 如果能在解析页面的上做选择就更好啦！
> 
> 直接把这个按钮移到首页吧

哈哈 等后面空了再调整一下
